use std::fmt::Write;

use crate::material::{Overlay, Surface};
use crate::metrics::Metric;
use crate::palette::{Palette, Role};
use crate::typography::{Face, Text};

pub fn stylesheet(palette: &Palette) -> String {
    let mut css = String::with_capacity(4096);
    let _ = writeln!(
        css,
        "/* {} — the LineXinBar design language, as custom properties.\n\
         \x20  Generated by lxb-toolkit {}. */",
        palette.name,
        crate::VERSION
    );
    let _ = writeln!(css, ":root {{");

    let _ = writeln!(css, "  /* The scale everything else is multiplied by. */");
    let _ = writeln!(css, "  --lxb-scale: 1;");

    let _ = writeln!(css, "\n  /* Colour, by role rather than by name. */");
    for role in Role::ALL {
        let color = palette.color(role);
        let _ = writeln!(css, "  --lxb-{}: {};", role.name(), color.hex());
    }

    let _ = writeln!(css, "\n  /* Sizes, against a 1080-tall screen. */");
    for metric in Metric::ALL {
        if metric.is_share() {
            let _ = writeln!(css, "  --lxb-{}: {};", metric.name(), metric.value());
        } else {
            let _ = writeln!(
                css,
                "  --lxb-{}: calc({}px * var(--lxb-scale));",
                metric.name(),
                metric.value()
            );
        }
    }

    let _ = writeln!(css, "\n  /* Type. */");
    let _ = writeln!(css, "  --lxb-font: \"{}\";", Face::Regular.family());
    let _ = writeln!(css, "  --lxb-font-weight: {};", Face::Regular.weight());
    let _ = writeln!(css, "  --lxb-font-weight-bold: {};", Face::Bold.weight());
    let _ = writeln!(css, "  --lxb-line-height: {};", Text::LINE);
    for text in Text::ALL {
        let _ = writeln!(
            css,
            "  --lxb-text-{}: calc({}px * var(--lxb-scale));",
            text.name(),
            text.size()
        );
    }

    let _ = writeln!(css, "\n  /* Motion. Never linear — see --lxb-ease. */");

    let _ = writeln!(css, "  --lxb-ease: cubic-bezier(0.65, 0, 0.35, 1);");
    for (name, seconds) in crate::motion_durations() {
        let _ = writeln!(
            css,
            "  --lxb-duration-{name}: {}ms;",
            (seconds * 1000.0) as u32
        );
    }

    let _ = writeln!(
        css,
        "\n  /* Glass, as far as a stylesheet can carry it: a blur and a lit\n\
         \x20    edge. The real material refracts what is behind it and cannot be\n\
         \x20    written here — see assets/shaders/lxb_glass.wgsl. */"
    );
    for surface in Surface::ALL {
        let glass = surface.glass();
        let name = surface.name();
        let _ = writeln!(
            css,
            "  --lxb-{name}-blur: calc({:.0}px * var(--lxb-scale));",
            glass.frost * crate::material::optics::BLUR_LEVELS * 6.0
        );
        let _ = writeln!(
            css,
            "  --lxb-{name}-rim: calc({}px * var(--lxb-scale));",
            (glass.depth / 8.0).round().max(1.0)
        );
        let _ = writeln!(css, "  --lxb-{name}-gloss: {};", glass.gloss);
    }

    let overlay = Overlay::Dialog.material();
    let _ = writeln!(
        css,
        "\n  /* One layered pane for both context menus and general dialogs. */"
    );
    for (name, value) in [
        ("radius", overlay.radius),
        ("light-inset", overlay.light_inset),
        ("header-height", overlay.header_height),
        ("foot-height", overlay.foot_height),
        ("rim-width", overlay.rim_width),
    ] {
        let _ = writeln!(
            css,
            "  --lxb-overlay-{name}: calc({value}px * var(--lxb-scale));"
        );
    }
    for (name, value) in [
        ("stain", overlay.stain),
        ("header-x", overlay.header_x),
        ("header-width", overlay.header_width),
        ("header-height-share", overlay.header_height_share),
        ("header-light", overlay.header_light),
        ("foot-x", overlay.foot_x),
        ("foot-width", overlay.foot_width),
        ("foot-height-share", overlay.foot_height_share),
        ("foot-light", overlay.foot_light),
        ("rim", overlay.rim),
    ] {
        let _ = writeln!(css, "  --lxb-overlay-{name}: {value};");
    }

    let _ = writeln!(css, "}}");
    css
}

pub fn stylesheet_named(name: &str) -> Option<String> {
    crate::palette::palette(name).map(stylesheet)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_token_is_in_it_under_its_own_name() {
        let css = stylesheet(&crate::palette::PURPLE);
        for role in Role::ALL {
            assert!(
                css.contains(&format!("--lxb-{}:", role.name())),
                "{}",
                role.name()
            );
        }
        for metric in Metric::ALL {
            assert!(
                css.contains(&format!("--lxb-{}:", metric.name())),
                "{}",
                metric.name()
            );
        }
        for text in Text::ALL {
            assert!(css.contains(&format!("--lxb-text-{}:", text.name())));
        }
        for (name, _) in crate::motion_durations() {
            assert!(css.contains(&format!("--lxb-duration-{name}:")));
        }
        for name in [
            "radius",
            "stain",
            "light-inset",
            "header-x",
            "header-width",
            "header-height",
            "header-height-share",
            "header-light",
            "foot-x",
            "foot-width",
            "foot-height",
            "foot-height-share",
            "foot-light",
            "rim",
            "rim-width",
        ] {
            assert!(css.contains(&format!("--lxb-overlay-{name}:")), "{name}");
        }
    }

    #[test]
    fn the_colours_are_the_authored_ones() {
        let css = stylesheet(&crate::palette::PURPLE);
        assert!(css.contains("--lxb-accent: #8b5cf6;"));
        assert!(css.contains("--lxb-danger: #e0533a;"));
        let blue = stylesheet_named("blue").expect("found by name, any case");
        assert!(blue.contains("--lxb-accent: #3b82f6;"));
        assert!(stylesheet_named("mauve").is_none());
    }

    #[test]
    fn it_is_a_block_a_stylesheet_can_take() {
        let css = stylesheet(&crate::palette::RED);
        assert!(css.contains(":root {"));
        assert!(css.trim_end().ends_with('}'));
        assert_eq!(css.matches('{').count(), css.matches('}').count());
        assert!(css.contains("--lxb-scale: 1;"));
        assert!(css.contains("var(--lxb-scale)"), "nothing scales with it");
    }

    #[test]
    fn the_easing_is_never_linear() {
        let css = stylesheet(&crate::palette::PURPLE);
        assert!(css.contains("--lxb-ease: cubic-bezier("));
        assert!(
            !css.contains(": linear"),
            "a token was handed out as a linear ramp"
        );
    }
}
